"""
Create a combined dashboard that links to both the report and analysis.
"""
from pathlib import Path
from jinja2 import Template
from datetime import datetime

DASHBOARD_TEMPLATE = Template("""
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Financial Dashboard</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
        
        .header {
            text-align: center;
            color: white;
            margin-bottom: 40px;
        }
        
        .header h1 {
            font-size: 3em;
            margin-bottom: 10px;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.2);
        }
        
        .header p {
            font-size: 1.2em;
            opacity: 0.9;
        }
        
        .cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 30px;
            margin-bottom: 30px;
        }
        
        .card {
            background: white;
            border-radius: 12px;
            padding: 40px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.2);
            transition: transform 0.3s, box-shadow 0.3s;
            text-decoration: none;
            color: inherit;
            display: block;
        }
        
        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 15px 40px rgba(0,0,0,0.3);
        }
        
        .card-icon {
            font-size: 4em;
            text-align: center;
            margin-bottom: 20px;
        }
        
        .card h2 {
            color: #667eea;
            font-size: 1.8em;
            margin-bottom: 15px;
            text-align: center;
        }
        
        .card p {
            color: #666;
            line-height: 1.6;
            text-align: center;
        }
        
        .card.report {
            border-top: 4px solid #667eea;
        }
        
        .card.analysis {
            border-top: 4px solid #f093fb;
        }
        
        .card.visualization {
            border-top: 4px solid #4facfe;
        }
        
        .footer {
            text-align: center;
            color: white;
            margin-top: 40px;
            opacity: 0.8;
        }
        
        .timestamp {
            text-align: center;
            color: white;
            margin-top: 20px;
            opacity: 0.7;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>💰 Financial Dashboard</h1>
            <p>Your Complete Financial Overview</p>
        </div>
        
        <div class="cards">
            <a href="report.html" class="card report">
                <div class="card-icon">📊</div>
                <h2>Financial Report</h2>
                <p>View your complete financial snapshot with cash flow, categories, debt analysis, and recent transactions.</p>
            </a>
            
            <a href="analysis_visualization.html" class="card visualization">
                <div class="card-icon">🤖</div>
                <h2>AI Analysis</h2>
                <p>ChatGPT's insights, recommendations, and budget analysis in a beautiful visual format.</p>
            </a>
            
            <a href="chatgpt_analysis.txt" class="card analysis">
                <div class="card-icon">📝</div>
                <h2>Raw Analysis</h2>
                <p>View the original text analysis from ChatGPT for easy copying and sharing.</p>
            </a>
        </div>
        
        <div class="timestamp">
            Last updated: {{ timestamp }}
        </div>
        
        <div class="footer">
            <p>Generated by Finance API • Monarch Money Integration</p>
        </div>
    </div>
</body>
</html>
""")

def main():
    """Create dashboard HTML."""
    base_dir = Path(__file__).parent.parent
    output_dir = base_dir / "data" / "outputs"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    html = DASHBOARD_TEMPLATE.render(timestamp=timestamp)
    
    dashboard_path = output_dir / "dashboard.html"
    dashboard_path.write_text(html, encoding='utf-8')
    
    print(f"[OK] Dashboard created: {dashboard_path}")
    print(f"   Open this file manually to access all your financial reports!")

if __name__ == "__main__":
    main()

